#!/usr/bin/env bash
set -euo pipefail

REPO="beiaduo/port-shaper"
BIN_NAME="port-shaper"
INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/port-shaper"
ENV_FILE="${CONF_DIR}/env"
SERVICE_FILE="/etc/systemd/system/port-shaper.service"
CLI_LINK="/usr/local/bin/port-shaper"
DOWN_MODE_DEFAULT="police"           # 下载限速模式: police 或 ifb
DEV_DEFAULT="eth0"                   # 默认网卡

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64)  echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *)
      echo "Unsupported arch: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

random_port() {
  python3 - <<'PY'
import random; print(random.randint(20000,60000))
PY
}

random_token() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import uuid,hashlib
u=uuid.uuid4().hex
print(hashlib.sha256(u.encode()).hexdigest())
PY
  elif command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

random_suffix() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import os,base64
print(base64.urlsafe_b64encode(os.urandom(12)).decode().rstrip('='))
PY
  elif command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 12 | tr '+/' '-_' | tr -d '='
  else
    date +%s%N | md5sum | cut -c1-16
  fi
}

public_ip() {
  for cmd in \
    "curl -fsS --max-time 3 https://api.ipify.org" \
    "curl -fsS --max-time 3 https://ifconfig.me" \
    "dig +short myip.opendns.com @resolver1.opendns.com"
  do
    IP=$(bash -lc "$cmd" 2>/dev/null || true)
    if [[ -n "${IP:-}" ]]; then echo "$IP"; return; fi
  done
  echo "0.0.0.0"
}

need_pkg() {
  dpkg -s "$1" >/dev/null 2>&1 || sudo apt-get install -y "$1"
}

install_deps() {
  sudo apt-get update
  need_pkg iproute2
  need_pkg iptables
  need_pkg curl
  need_pkg ca-certificates
  need_pkg python3 || true
  need_pkg dnsutils || true
}

download_binary() {
  local arch="$1"
  local url bin_file tmp
  case "$arch" in
    amd64)  bin_file="${BIN_NAME}-linux-amd64" ;;
    arm64)  bin_file="${BIN_NAME}-linux-arm64" ;;
  esac
  url="https://github.com/${REPO}/releases/latest/download/${bin_file}"

  tmp="$(mktemp -d)"
  echo "Downloading ${url} ..."
  curl -fL --retry 3 --connect-timeout 5 -o "${tmp}/${BIN_NAME}" "$url"
  sudo install -m 0755 "${tmp}/${BIN_NAME}" "${INSTALL_DIR}/${BIN_NAME}"
  rm -rf "$tmp"
}

write_env() {
  local port="$1" token="$2" suffix="$3"
  sudo mkdir -p "$CONF_DIR"
  sudo tee "$ENV_FILE" >/dev/null <<EOF
# Auto-generated by install.sh
API_TOKEN=${token}
PORT=${port}
DEV=${DEV_DEFAULT}
BASE_PATH=/${suffix}
DOWN_MODE=${DOWN_MODE_DEFAULT}
IFB_ENABLE=1
EOF
  sudo chmod 600 "$ENV_FILE"
}

write_service() {
  sudo tee "$SERVICE_FILE" >/dev/null <<'EOF'
[Unit]
Description=Port Shaper API service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/port-shaper/env
ExecStart=/usr/local/bin/port-shaper
Restart=on-failure
RestartSec=2s
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN
NoNewPrivileges=true
ProtectSystem=full
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable port-shaper
}

write_cli() {
  local public_ip="$1"
  sudo tee "$CLI_LINK" >/dev/null <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
ENV="/etc/port-shaper/env"

if [[ ! -f "$ENV" ]]; then
  echo "env file not found: $ENV"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV"

LOCAL_IP="127.0.0.1"
PUBLIC_IP_ARG="${1:-}"

if [[ -z "$PUBLIC_IP_ARG" ]]; then
  if command -v curl >/dev/null 2>&1; then
    PUBLIC_IP_ARG="$(curl -fsS --max-time 3 https://api.ipify.org || true)"
  fi
  [[ -z "$PUBLIC_IP_ARG" ]] && PUBLIC_IP_ARG="0.0.0.0"
fi

show_info() {
  echo "================ Port Shaper ================"
  echo "Dev:          ${DEV}"
  echo "Port:         ${PORT}"
  echo "Base Path:    ${BASE_PATH}"
  echo "Down Mode:    ${DOWN_MODE}"
  echo "IFB Enable:   ${IFB_ENABLE}"
  echo "API Token:    ${API_TOKEN}"
  echo "---------------------------------------------"
  echo "Local URL:    http://${LOCAL_IP}:${PORT}${BASE_PATH}"
  echo "Public URL:   http://${PUBLIC_IP_ARG}:${PORT}${BASE_PATH}"
  echo "============================================="
}

menu() {
  while true; do
    echo
    echo " 1) 查看访问信息"
    echo " 2) 查看 systemd 状态"
    echo " 3) 查看最近日志"
    echo " 4) 重启服务"
    echo " 0) 退出"
    read -rp "请选择: " c
    case "$c" in
      1) show_info ;;
      2) systemctl status port-shaper --no-pager ;;
      3) journalctl -u port-shaper -n 100 --no-pager ;;
      4) systemctl restart port-shaper && echo "已重启" ;;
      0) exit 0 ;;
      *) echo "无效选择" ;;
    esac
  done
}

if [[ -t 1 ]]; then
  menu
else
  show_info
fi
EOF
  sudo chmod +x "$CLI_LINK"
}

start_service() {
  sudo systemctl restart port-shaper
  sleep 1
  sudo systemctl --no-pager --full status port-shaper || true
}

main() {
  install_deps
  ARCH="$(detect_arch)"
  PORT="$(random_port)"
  TOKEN="$(random_token)"
  SUFFIX="$(random_suffix)"
  PUBIP="$(public_ip)"

  download_binary "$ARCH"
  write_env "$PORT" "$TOKEN" "$SUFFIX"
  write_service
  start_service
  write_cli "$PUBIP"

  echo
  echo "=========== INSTALL SUMMARY ==========="
  echo "Binary:      ${INSTALL_DIR}/${BIN_NAME}"
  echo "Config:      ${ENV_FILE}"
  echo "Service:     ${SERVICE_FILE}"
  echo "---------------------------------------"
  echo "Local URL:   http://127.0.0.1:${PORT}/${SUFFIX}"
  echo "Public URL:  http://${PUBIP}:${PORT}/${SUFFIX}"
  echo "API Token:   ${TOKEN}"
  echo "Dev:         ${DEV_DEFAULT}"
  echo "Down Mode:   ${DOWN_MODE_DEFAULT}"
  echo "IFB Enable:  1"
  echo "---------------------------------------"
  echo "本机查看信息（带菜单）： port-shaper"
  echo "非交互输出（传公网IP）：  port-shaper ${PUBIP}"
  echo "======================================="
}

main "$@"